### PR TITLE
Add discord as a login option

### PR DESCRIPTION
**Pull request by raithos**
Someone suggested adding discord as a login option. omniauth has a discord option so I went and added it to web.ru

### CODE REVIEW

**Comment by geordanr** [comment]
I was hoping this would be fairly straightforward, but I tried deploying this (after setting up OAuth on Discord and setting the config to have the client ID and secret) but something seems to be failing.  It isn't logging any errors; will need to investigate more.

**Comment by geordanr** [comment]
I think I know what the problem is: in [backend.coffee](https://github.com/raithos/xwing/blob/master/coffeescripts/backend.coffee#L392), we iterate over each returned OAuth2 method to create a button for that method.  But adding a new Discord method causes that to look for a nonexistent key in `method_metadata` which blows up and prevents `ui_ready` from being set to true, which in turn makes clicking the "Log In" button do nothing (which is the behavior I was seeing, and incidentally doesn't log any error to the console).

So the thing to do here is update `backend.coffee` to be resilient against unexpected methods (just skip them), and then once that's deployed I should be able to deploy the new version of the backend that serves up the new Discord OAuth2 method.

**Comment by raithos** [comment]
since im working on backend.coffee right now to include discord as an option in method_metadata right now I can push that for u real quick

**Comment by geordanr** [comment]
Or, I guess, just add a `discord` key to `method_metadata`, which won't show up until the backend is updated.  That's more straightforward 🤷‍♀️ 

Heh your comment just appeared while I was typing this

**Comment by raithos** [comment]
I just pushed that change live. give it a go!

**Comment by geordanr** [comment]
Well, it sort of works!  I didn't finish setting up the Discord OAuth stuff apparently.  Gonna roll that back while I work on that.

**Comment by raithos** [comment]
Cool while you do that I'm going to try to get font awesome to work on the latest version lol

**Comment by geordanr** [comment]
Looks good, was able to successfully log in via Discord!

**Pull request merged**
